#!/bin/bash
source cuter
cd
cd Downloads/
x=1
while [ $x -eq 1 ]; do
    read -p "Was willst du installieren? (1: .deb, 2: .tar.gz/tar.xz/tar.bz2, 3: .jar 4: .rpm)" Dateiendung
    if [ $Dateiendung == 2 ]; then
      cuter "$( ls )" . "s"
    else
        ls
    fi
    read -p "Welche von diesen gennanten Dateien willst du installieren?" Dateiname

    if [ $Dateiendung == 1 ]; then
        sudo dpkg -i $Dateiname
        sudo apt install -f
        sudo dpkg -i $Dateiname
        mv $Dateiname ~/Speicher/Downloads
    fi

    if [ $Dateiendung == 2 ]; then
        tar -xf $Dateiname.tar*
        mv $Dateiname ~/programs/.
        mv $Dateiname.tar* ~/Speicher/Downloads
    fi

    if [ $Dateiendung == 3 ]; then
        java -jar $Dateiname
        mv $Dateiname ~/Speicher/Downloads
    fi

    if [ $Dateiendung == 4 ]; then
        rpm -ivh $Dateiname --nodeps --force
        mv $Dateiname ~/Speicher/Downloads
    fi

    read -p "Willst du das Programm noch mal ausführen? 1:Ja,0:Nein" x
done
