#!/bin/bash

source ${scripts}/farbcodes.sh
source ${scripts}/git_status

function installer() {
  echo -e "${1}\n${2}" | ${scripts}/Installer
}

function update() {
  ${scripts}/updater
}

function bsed() {
  echo $3 | ${scripts}/bsed $1 $2
}
