#!/bin/bash

source ${home}/shell_scripts/farbcodes.sh
source ${home}/shell_scripts/git_status

function installer() {
  echo -e "${1}\n${2}" | ${home}/shell_scripts/Installer
}

function update() {
  ${home}/shell_scripts/updater
}
