#!/bin/bash

git config --global core.editor "vim"
read -p "Your Git Username: " name
git config --global user.name $name
read -p "Your Git Email Address: " email
git config --global user.email $email
